version: "3.8"

networks:
  default:
    driver: bridge

services:

  mysqldb:
    container_name: mysqldb
    image: mysql:8.0
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: homestead
      MYSQL_PASSWORD: root
    volumes:
      - mysqldriver:/var/lib/mysql:rw
    networks:
      - default
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    ports:
      - 3306:3306

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "3003:80"
    environment:
      PMA_HOST: mysqldb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m30s
      timeout: 20s
      retries: 3
    depends_on:
      - mysqldb

  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redisdriver:/data
    networks:
      - default

  mongo:
    container_name: mongo
    image: mongo:6.0.10
    volumes:
      - mongodriver:/data
    ports:
      - 27017:27017
    restart: always
    networks:
      - default
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  mysqldriver:
  mongodriver:
  redisdriver: