version: "3.8"

networks:
  default:
    driver: bridge

services:

  mysqldb:
    container_name: mysqldb
    image: mysql:8.0
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: homestead
      MYSQL_PASSWORD: root
    volumes:
      - mysqldriver:/var/lib/mysql:rw
    networks:
      - default
    restart: always
    ports:
      - 3306:3306

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "3003:80"
    environment:
      PMA_HOST: mysqldb
    networks:
      - default
    depends_on:
      - mysqldb

  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redisdriver:/data
    networks:
      - default

volumes:
  mysqldriver:
  redisdriver: